### ISSUE TITLE
AsRecursive() doesn't look to work on a base view model

### ISSUE THREAD

**Issue by AndyButland** [JimBobSquarePants/UmbMapper#4]
Thanks for putting this out James - started to have a look into it, comparing how we'd use it with our usual mapping solution, and coming together quite nicely so far.

Seem to be running into this issue though.  I've got a "base page view model" that defines various fields found on all pages.  Each actual page view model inherits from that.  It appears if I try to map a field recursively on the base page view model, it doesn't use that setting when mapping the derived class - `UmbracoPropertyMapper.Map()` calls `GetPropertyValue` with the `recursive` parameter set to `false`.

To show the simplest case it seems that this fails:

``` c#
    public class BasePageViewModel
    {
        public string SiteTitle { get; set; }
    }
	
    public class TextPageViewModel : BasePageViewModel
    {
    }
	
    public class BasePageViewModelMap : UmbMapperConfig<BasePageViewModel>
    {
        public BasePageViewModelMap()
        {
            MapAll();
            AddMap(p => p.SiteTitle).AsRecursive();
        }
    }
	
    public class TextPageViewModelMap : UmbMapperConfig<TextPageViewModel>
    {
        public TextPageViewModelMap()
        {
            MapAll();
        }
    }

    UmbMapperRegistry.AddMapper(new BasePageViewModelMap());
    UmbMapperRegistry.AddMapper(new TextPageViewModelMap());
```

But this works:

``` c#
    public class BasePageViewModel
    {
    }
	
    public class TextPageViewModel : BasePageViewModel
    {
        public string SiteTitle { get; set; }
    }
	
    public class BasePageViewModelMap : UmbMapperConfig<BasePageViewModel>
    {
        public BasePageViewModelMap()
        {
            MapAll();
        }
    }
	
    public class TextPageViewModelMap : UmbMapperConfig<TextPageViewModel>
    {
        public TextPageViewModelMap()
        {
            MapAll();
            AddMap(p => p.SiteTitle).AsRecursive();
        }
    }

    UmbMapperRegistry.AddMapper(new BasePageViewModelMap());
    UmbMapperRegistry.AddMapper(new TextPageViewModelMap());
```

**Comment by JimBobSquarePants** [comment]
Hi Andy,

Thanks for giving this a try; I'm glad you're enjoying it.

There's actually a mistake in the way you're setting up the mappings.

``` c#
public class BasePageViewModelMap : UmbMapperConfig<BasePageViewModel>
{
    public BasePageViewModelMap()
    {
        MapAll();
        AddMap(p => p.SiteTitle).AsRecursive();
    }
}
	
public class TextPageViewModelMap : UmbMapperConfig<TextPageViewModel>
{
    public TextPageViewModelMap()
    {
        MapAll();
    }
}
```
If you look at the way you've set up the mapping you've actually defined two separate mappers with no knowledge of each other. The mappers calculate all the required information for the type when registered (hence why it's so fast) with no runtime calculation against those types. There's no way for `TextPageViewModelMap` to know about the recursive mapping.

What you need to do is use inheritance on the mappers themselves as well as the classes so that the inherited mapper has knowledge of the base type mapper.

e.g 

``` c#
public class BasePageViewModelMap<T> : UmbMapperConfig<T>
    where T : BasePageViewModel
{
    public BasePageViewModelMap()
    {
        this.MapAll();
        this.AddMap(m => m.SiteTitle).AsRecursive();
    }
}

public class TextPageViewModelMap : BasePageViewModelMap<TextPageViewModel>
{
    public TextPageViewModelMap()
    {
        MapAll();
    }
}
```

You don't then even need to register the `BasePageViewModelMap` mapper.

I hope that makes sense.

Cheers

James

P.S I'm gonna be pushing a new version soon with much simpler logic internally, less allocations, and much, much faster factory mappings that allow polymorphic mapping.

**Comment by AndyButland** [comment]
Nice. Makes sense, thanks.
